name: Bygg og deploy pages

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6 # ratchet:exclude
      - name: Build notebooks
        env:
          INPUT_SALT: ${{ secrets.INPUT_SALT }}
        run: |
         make docker-clerk
         make docker-clay
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4 # ratchet:exclude

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5 # ratchet:exclude
